# Generated by Microsoft365DSC from https://export.microsoft365dsc.com on 11/7/2023, 3:28:24 PM
# Visit https://microsoft365dsc.com for more information

# Getting client credential
$Credential = Get-Credential

# Exporting resources using credentials
Export-M365DSCConfiguration -Components @("PPPowerAppsEnvironment", "PPTenantIsolationSettings", "PPTenantSettings") -Credential $Credential